Traceback (most recent call last):
  File "/Users/michal/Dropbox/OER-text/CS211-text/env/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/michal/Dropbox/OER-text/CS211-text/env/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/michal/Dropbox/OER-text/CS211-text/env/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/michal/Dropbox/OER-text/CS211-text/env/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/michal/Dropbox/OER-text/CS211-text/env/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/michal/Dropbox/OER-text/CS211-text/env/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/michal/Dropbox/OER-text/CS211-text/env/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
shapes = [ Rect(Point(2,2), Point(3,3)), 
           Square(Point(0,0), 3), 
           Triangle(Point(0,0), Point(0, 4), Point(4,0)) ]
           
for shape in shapes: 
    print(shape.area())
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [16][0m, in [0;36m<cell line: 5>[0;34m()[0m
[1;32m      1[0m shapes [38;5;241m=[39m [ Rect(Point([38;5;241m2[39m,[38;5;241m2[39m), Point([38;5;241m3[39m,[38;5;241m3[39m)), 
[1;32m      2[0m            Square(Point([38;5;241m0[39m,[38;5;241m0[39m), [38;5;241m3[39m), 
[1;32m      3[0m            Triangle(Point([38;5;241m0[39m,[38;5;241m0[39m), Point([38;5;241m0[39m, [38;5;241m4[39m), Point([38;5;241m4[39m,[38;5;241m0[39m)) ]
[1;32m      5[0m [38;5;28;01mfor[39;00m shape [38;5;129;01min[39;00m shapes: 
[0;32m----> 6[0m     [38;5;28mprint[39m([43mshape[49m[38;5;241;43m.[39;49m[43marea[49m[43m([49m[43m)[49m)

Input [0;32mIn [13][0m, in [0;36mTriangle.area[0;34m(self)[0m
[1;32m     23[0m ix, iy [38;5;241m=[39m normal_intersect([38;5;28mself[39m[38;5;241m.[39mp2[38;5;241m.[39mx, [38;5;28mself[39m[38;5;241m.[39mp2[38;5;241m.[39my,
[1;32m     24[0m                           [38;5;28mself[39m[38;5;241m.[39mp3[38;5;241m.[39mx, [38;5;28mself[39m[38;5;241m.[39mp3[38;5;241m.[39my,
[1;32m     25[0m                           [38;5;28mself[39m[38;5;241m.[39mp1[38;5;241m.[39mx, [38;5;28mself[39m[38;5;241m.[39mp1[38;5;241m.[39my)
[1;32m     26[0m intercept [38;5;241m=[39m Point(ix, iy)
[0;32m---> 27[0m base [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mp2[49m[38;5;241;43m.[39;49m[43mdist[49m([38;5;28mself[39m[38;5;241m.[39mp3)
[1;32m     28[0m height [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mp1[38;5;241m.[39mdist(intercept)
[1;32m     29[0m [38;5;28;01mreturn[39;00m [38;5;241m0.5[39m [38;5;241m*[39m base [38;5;241m*[39m height

[0;31mAttributeError[0m: 'Point' object has no attribute 'dist'
AttributeError: 'Point' object has no attribute 'dist'

